[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "editable-python-deps"
version = "0.1.0"
description = ""
authors = [
    {name = "Ian Vermes",email = "iv3@sanger.ac.uk"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "click (>=8.3.2,<9.0.0)",
    "tomlkit (>=0.14.0,<0.15.0)",
    "prompt-toolkit (>=3.0.52,<4.0.0)",
]
packages = [{ include = "editable_python_deps", from = "src" }]

[project.scripts]
editable-python-deps = "editable_python_deps.cli:run_cli"

[dependency-groups]
dev = [
    "black[jupyter] (>=25.1.0,<26.0.0)",
    "ipython",
    "pytest",
    "pre-commit",
    "pytest-subprocess (>=1.5.4,<2.0.0)"
]

[tool.pytest.ini_options]
# Pytest setting go here.
#
# For more info, see https://docs.pytest.org/en/8.2.x/reference/customize.html#pyproject-toml
# e.g. uncomment the following line to enable verbose output
# addopts = "-v"
